Repairs
eni020/ivt-lab pull request #3
Opened 2020-05-09 09:31 UTC by eni020

2020-05-09 09:33 UTC, eni020 commented
Repaired three problems of TorpedoStore.java

2020-05-10 08:40 UTC, sij1nk requested changes
Move Random generator to class field

2020-05-10 08:40 UTC, anguaive commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +      throw new IllegalArgumentException("numberOfTorpedos");
Ok

2020-05-10 08:40 UTC, anguaive commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +      this.torpedoCount -= numberOfTorpedos;
Ok

2020-05-10 08:40 UTC, anguaive commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +    double r = new Random().nextDouble();
Itt szerintem az az elvart megoldas, hogy a Random object-et kirakod osztalyvaltozoba es a konstruktorban hozod letre (most minden fuggvenyhivaskor ujat hozunk letre, ami plusz munka)

2020-05-10 08:49 UTC, sij1nk approved these changes
Szuper

2020-05-10 08:49 UTC, anguaive commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +    this.generator = new Random();
Ok

2020-05-10 08:50 UTC, merged